"""
Report Helper Utilities: Cutadapt CLI generator, DADA2 truncation calculator,
MultiQC export module, and TSV matrix exporter.
"""

import json
from pathlib import Path
from typing import Dict, Any, List, Optional, Tuple, Union


def generate_cutadapt_command(
    sample_name: str,
    r1_path: str,
    r2_path: Optional[str],
    detected_primers: List[Dict[str, Any]],
    is_long_read: bool = False,
) -> str:
    """
    Generates exact ready-to-copy Cutadapt or Chopper CLI commands based on detected primers.
    """
    if not detected_primers:
        return "# No untrimmed primers detected. Read sequences appear clean."

    top_fwd = None
    top_rev = None

    for p in detected_primers:
        name = p.get("primer_name", "")
        seq = p.get("sequence", "")
        if "F" in name or "FWD" in name or "1F" in name or "27F" in name or "341F" in name or "515F" in name:
            if not top_fwd:
                top_fwd = (name, seq)
        elif "R" in name or "REV" in name or "338R" in name or "805R" in name or "806R" in name or "1492R" in name:
            if not top_rev:
                top_rev = (name, seq)

    if not top_fwd and detected_primers:
        top_fwd = (detected_primers[0]["primer_name"], detected_primers[0]["sequence"])
    if not top_rev and len(detected_primers) > 1:
        top_rev = (detected_primers[1]["primer_name"], detected_primers[1]["sequence"])

    fwd_seq = top_fwd[1] if top_fwd else "FORWARD_PRIMER"
    rev_seq = top_rev[1] if top_rev else "REVERSE_PRIMER"

    if is_long_read:
        return (
            f"# Nanopore / PacBio Chopper / Cutadapt Command for {sample_name}:\n"
            f"cutadapt -g {fwd_seq} -a {rev_seq} --revcomp --error-rate 0.15 \\\n"
            f"  -o {sample_name}_trimmed.fastq.gz {r1_path}"
        )
    elif r2_path:
        return (
            f"# Illumina Paired-End Cutadapt Command for {sample_name}:\n"
            f"cutadapt -g {fwd_seq} -G {rev_seq} \\\n"
            f"  -o {sample_name}_trimmed_R1.fastq.gz -p {sample_name}_trimmed_R2.fastq.gz \\\n"
            f"  --discard-untrimmed --minimum-length 100 \\\n"
            f"  {r1_path} {r2_path}"
        )
    else:
        return (
            f"# Illumina Single-End Cutadapt Command for {sample_name}:\n"
            f"cutadapt -g {fwd_seq} --discard-untrimmed --minimum-length 100 \\\n"
            f"  -o {sample_name}_trimmed.fastq.gz {r1_path}"
        )


def calculate_dada2_recommendation(
    stats: Dict[str, Any],
    target_region: str,
    is_paired: bool = False,
) -> Dict[str, Any]:
    """
    Calculates optimal DADA2 truncation length parameters (trunc_len_f, trunc_len_r)
    based on per-base quality scores and target amplicon length overlap requirements.
    """
    mean_len = int(round(stats.get("mean_read_length", 250)))
    qual_matrix = stats.get("per_base_quality", {})

    # Default truncation suggestions
    trunc_f = mean_len
    trunc_r = mean_len

    if is_paired:
        # For 2x250 or 2x300 16S V3-V4 (target ~460bp), overlap requires trunc_f + trunc_r >= 480bp
        target_len = 460 if "v3v4" in target_region.lower() or "16s" in target_region.lower() else 300
        min_combined = target_len + 20

        trunc_f = min(mean_len, max(220, mean_len - 10))
        trunc_r = min(mean_len, max(180, mean_len - 40))

        if (trunc_f + trunc_r) < min_combined:
            trunc_f = min(mean_len, min_combined - trunc_r)

        dada2_str = f"truncLen=c({trunc_f}, {trunc_r}), maxN=0, maxEE=c(2, 5), truncQ=2"
    else:
        trunc_f = min(mean_len, max(150, mean_len - 15))
        dada2_str = f"truncLen={trunc_f}, maxN=0, maxEE=2, truncQ=2"

    return {
        "trunc_len_f": trunc_f,
        "trunc_len_r": trunc_r if is_paired else None,
        "dada2_code": dada2_str,
        "recommendation_text": f"Recommended DADA2 parameters for {target_region}: `{dada2_str}`"
    }


def export_multiqc_json(full_data: Dict[str, Any], output_path: Union[str, Path]):
    """
    Exports MultiQC custom content JSON file (_ampliqc_mqc.json) for seamless Nextflow / MultiQC integration.
    """
    p = Path(output_path)
    p.parent.mkdir(parents=True, exist_ok=True)

    sample_name = full_data.get("sample_name", "sample")
    summary = full_data.get("summary", {})
    context_eval = full_data.get("context_evaluation", {})
    metadata = context_eval.get("metadata", {})

    multiqc_content = {
        "id": "ampliqc_summary",
        "section_name": "ampliQC Amplicon Context Summary",
        "description": "Context-aware Amplicon Quality Control metrics generated by ampliQC.",
        "plot_type": "table",
        "pconfig": {
            "id": "ampliqc_table",
            "title": "ampliQC Amplicon Metrics",
        },
        "data": {
            sample_name: {
                "Total Reads": summary.get("total_reads", 0),
                "Mean Length (bp)": summary.get("mean_read_length", 0),
                "GC Content (%)": summary.get("overall_gc_content", 0.0),
                "Duplication Rate (%)": summary.get("duplication_rate", 0.0),
                "Overall Status": context_eval.get("overall_status", "UNKNOWN"),
                "Target Region": metadata.get("target_region", "N/A"),
                "Primary Primer": metadata.get("primary_primer", "N/A"),
                "Trimming Status": metadata.get("trimming_status", "N/A"),
            }
        }
    }

    with open(p, "w", encoding="utf-8") as f:
        json.dump(multiqc_content, f, indent=2)


def export_tsv(batch_results: List[Dict[str, Any]], output_path: Union[str, Path]):
    """
    Exports multi-sample summary matrix in TSV format.
    """
    p = Path(output_path)
    p.parent.mkdir(parents=True, exist_ok=True)

    headers = [
        "Sample",
        "Context",
        "Status",
        "Total_Reads",
        "Mean_Length",
        "GC_Content_Pct",
        "Duplication_Rate_Pct",
        "Target_Region",
        "Primary_Primer",
        "Trimming_Status",
        "Recommended_Pipeline"
    ]

    lines = ["\t".join(headers)]
    for r in batch_results:
        sample = r.get("sample_name", "N/A")
        summary = r.get("summary", {})
        ctx_eval = r.get("context_evaluation", {})
        meta = ctx_eval.get("metadata", {})

        row = [
            sample,
            ctx_eval.get("context", "Amplicon"),
            ctx_eval.get("overall_status", "PASS"),
            str(summary.get("total_reads", 0)),
            str(summary.get("mean_read_length", 0)),
            str(summary.get("overall_gc_content", 0.0)),
            str(summary.get("duplication_rate", 0.0)),
            meta.get("target_region", "N/A"),
            meta.get("primary_primer", "N/A"),
            meta.get("trimming_status", "N/A"),
            meta.get("recommended_pipeline", "N/A"),
        ]
        lines.append("\t".join(row))

    with open(p, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
